DELETE FROM STUDENT s2 WHERE id IN (SELECT student_id FROM mark WHERE MARK>4);
delete FROM STUDENT WHERE id IN (SELECT DISTINCT student_id FROM mark WHERE mark<4);
delete FROM PAYMENTTYPE WHERE name='DAILY';
DELETE FROM mark WHERE mark<7;
