ALTER TABLE PUBLIC.MARK DROP CONSTRAINT CONSTRAINT_23;
ALTER TABLE MARK
ADD CONSTRAINT mark_student_id_fkey foreign key (student_id) references student(id)
    ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE PUBLIC.PAYMENT DROP CONSTRAINT  CONSTRAINT_FBE;
ALTER TABLE PAYMENT
ADD CONSTRAINT payment_student_id_fkey foreign key (student_id) references student(id)
    ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE PUBLIC.PAYMENT DROP CONSTRAINT CONSTRAINT_FB;
ALTER TABLE PAYMENT
ADD CONSTRAINT payment_type_fkey foreign key (type_id) references PAYMENTTYPE(id)
    ON DELETE CASCADE ON UPDATE NO ACTION;
