SELECT * FROM SUBJECT WHERE id in(SELECT SUBJECT_id FROM MARK GROUP by SUBJECT_id HAVING avg(mark)>(SELECT avg(mark) FROM MARK));
SELECT * FROM STUDENT WHERE id IN (SELECT student_id FROM (SELECT student_id,avg(amount) AS am FROM PAYMENT GROUP BY student_id HAVING am<(SELECT avg(AMOUNT) FROM PAYMENT)));
